#!/bin/bash -exu
# vim: set ft=sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

TMPDIR=${TMPDIR:-/tmp}
source "$(dirname "$0")/common.sh"
payload="$(mktemp "${TMPDIR}/pulp-resource.XXXXXX")"
if [[ ${PULP_TESTING} == "true" ]]; then
  cat > "${payload}" <./payload
else
  cat > "${payload}" <&0
fi
pre_flight "${payload}"

### Check repo exists and get repo href
VERSIONS_HREF=$(http GET ${ENDPOINT}/pulp/api/v3/repositories/deb/apt/?name=$REPO_NAME Authorization:"$BASIC_AUTH" | jq -r '.results[0].versions_href')
if [ $VERSIONS_HREF = "null" ]; then
  VERSIONS_HREF=$(http POST ${ENDPOINT}/pulp/api/v3/repositories/deb/apt/ name="$REPO_NAME" Authorization:"$BASIC_AUTH" | jq -r '.versions_href')
fi
export VERSIONS_HREF

### Get versions
http GET ${ENDPOINT}${VERSIONS_HREF}?ordering=number Authorization:"$BASIC_AUTH" | jq -r ".results | map(select(.number >= ${REPO_VERSION})) | map({number})" >&3
