#!/bin/bash -exu
# vim: set ft=sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

TMPDIR=${TMPDIR:-/tmp}
source "$(dirname "$0")/common.sh"
payload="$(mktemp "${TMPDIR}/pulp-resource.XXXXXX")"
# cat > "${payload}" <./payload
cat > "${payload}" <&0
pre_flight "${payload}"

echo "Input not supported, implicit get does nothing"

echo $INPUT_VERSION >&3
