#!/bin/bash -exu
# vim: set ft=sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

TMPDIR=${TMPDIR:-/tmp}
source "$(dirname "$0")/common.sh"
payload="$(mktemp "${TMPDIR}/pulp-resource.XXXXXX")"
cat > "${payload}" <&0
pre_flight "${payload}"

UPLOAD_DEBUGS="$(jq -r '.params.debug // ""' < ${payload})"

# ### Check repo exists and get repo href
REPO_HREF=$(http GET ${ENDPOINT}/pulp/api/v3/repositories/${REPO_TYPE}/?name=${REPO_NAME} Authorization:"${BASIC_AUTH}" | jq -r '.results[0].pulp_href')
if [[ $REPO_HREF == "null" ]]; then
  REPO_HREF=$(http POST ${ENDPOINT}/pulp/api/v3/repositories/${REPO_TYPE}/ name="${REPO_NAME}" Authorization:"${BASIC_AUTH}" | jq -r '.pulp_href')
fi
export REPO_HREF

source "$(dirname "$0")/out.d/${PACKAGE_TYPE}.sh" "$@"

TASK_URL=$(http POST ${ENDPOINT}/pulp/api/v3/publications/${REPO_TYPE}/ repository="${REPO_HREF}" simple=true Authorization:"${BASIC_AUTH}" | jq -r '.task')
sleep 2
PUBLICATION_HREF=$(http GET ${ENDPOINT}${TASK_URL} Authorization:"${BASIC_AUTH}" | jq -r '.created_resources | first')

OLD_DIST_HREF=$(http GET ${ENDPOINT}/pulp/api/v3/distributions/${REPO_TYPE}/?base_path=${REPO_NAME} Authorization:"${BASIC_AUTH}" | jq -r '.results[0].pulp_href')
if [[ $OLD_DIST_HREF != "null" ]]; then
  http DELETE ${ENDPOINT}${OLD_DIST_HREF} Authorization:"${BASIC_AUTH}" | jq -r '.task'
  sleep 2
fi

TASK_URL=$(http POST ${ENDPOINT}/pulp/api/v3/distributions/${REPO_TYPE}/ publication="$PUBLICATION_HREF" name="${REPO_NAME}" base_path="${REPO_NAME}" Authorization:"${BASIC_AUTH}" | jq -r '.task')
sleep 2

DISTRIBUTION_HREF=$(http ${ENDPOINT}${TASK_URL} Authorization:"${BASIC_AUTH}" | jq -r '.created_resources | first')
export METADATA=$(http ${ENDPOINT}${DISTRIBUTION_HREF} Authorization:"${BASIC_AUTH}" | jq -cr 'to_entries | map({name: .key, value})')

VERSION_HREF=$(http GET ${ENDPOINT}${PUBLICATION_HREF} Authorization:"${BASIC_AUTH}" | jq -r '.repository_version')
export VERSION=$(http GET ${ENDPOINT}${VERSION_HREF} Authorization:"${BASIC_AUTH}" | jq -cr '{number: .number | tostring}')

jq -n "{version: $VERSION, metadata: $METADATA}" >&3